ebook_metadata:
  title: ༁ྃ༔ དམ་ཆོས་སྙིང་པོ་སྐོར་ལྔ་ལས༔ ཞལ་གདམས་སྙིང་པོ་འདུས་པ་བཞུགས་སོ༔
  authors:
  - མཛད་པ་པོ། གཏེར་ཆེན་མཆོག་གྱུར་གླིང་པ།
  sku: SHE-RTD-021
  layers:
  - book_title
  - author
web_metadata:
  title:
    en: A Collection of Advice from Guru Rinpoche’s Five Quintessential Dharmas
    bo: དམ་ཆོས་སྙིང་པོ་སྐོར་ལྔ་ལས༔ ཞལ་གདམས་སྙིང་པོ་འདུས་པ་བཞུགས༔
  collection:
    en: Treasury of Precious Termas–  Book 21
    bo: ''
  author:
    en: Terchen Chogyur Lingpa
    bo: ''
  pusblisher:
    en: Shechen Publications
    bo: ''
  sku: SHE-RTD-021
  category:
    en: Uncategorized
    bo: སྡེ་ཚན་མེད་པ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-RTD-021.epub
  description:
    en: ''
    bo: ''
